service: acorns

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${env:AWS_PROFILE}
  environment:
    S3_BASE_URL: ${env:S3_BASE_URL}
    BUCKET_NAME: ${env:S3_BUCKET_NAME}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}"
    - Effect: "Allow"
      Action: "s3:GetObject"
      Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}"

functions:
  # Existing clients checking in to see if a new update is available
  update:
    handler: handler.update
    events:
     - http:
         path: update/{platform}/{version}
         method: get
     - http:
         path: update/{platform}/{version}/RELEASES
         method: get
  # Download the latest release for new installs
  latest:
    handler: handler.latest
    events:
      - http:
          path: download/latest/{platform}
          method: get
  # Download a specific file
  download:
    handler: handler.download
    events:
      - http:
          path: download/{platform}/{version}/{file}
          method: get

plugins:
  - serverless-webpack
  - serverless-offline
