service: acorns

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${env:AWS_PROFILE}
  environment:
    S3_BASE_URL: ${env:S3_BASE_URL}
    BUCKET_NAME: ${env:S3_BUCKET_NAME}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}"
    - Effect: "Allow"
      Action: "s3:GetObject"
      Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}"

functions:
  # Existing clients checking in to see if a new release is available
  update:
    handler: update.check
    events:
     - http:
         path: update/{platform}/{version}
         method: get

  # # Handle a /latest URL for new users to download a version of the app (Different params for platforms?)
  # download:
  #   handler: download.latest
  #   events:
  #     - http:
  #         path: latest
  #         method: get

plugins:
  - serverless-offline
